# These are supported funding model platforms

github: ruge0326,rgcompany26]
patreon: tony03
open_collective: rgcompany26
ko_fi: rgcompany26
community_bridge: rgcompany26
liberapay: rgcompany26
issuehunt: rgcompany26
otechie: rgcompany26
